### PR TITLE
Add bh_adj function

### PR DESCRIPTION
**Pull request by zach-faunalytics**
the only file that needs review here is the bh_adj.R file. the rest are automatically update by the package creation library roxygen2.

### CODE REVIEW

**Review by jo-faunalytics — CHANGES_REQUESTED** [review]
This looks great, no concerns. I only have a couple of minor notes and don't think I need a walkthrough unless you spot something I misunderstood.

1. The name of the function should include '_lm' because it doesn't work for glm -- I checked with a model from Relative Effectiveness.
2. Can you include the adjusted p-value in the output table? Some (maybe all) of our previous studies have used `p.adjust(method = "BH")` which gives adjusted p-values so for consistency it would be nice to have the option of reporting the same way. If helpful, the code from Andrea's study was:
```
pvalues <- enframe(coef(summary(logistic_model))[2:11, 4], name = "variables", value = "pvalues")
adjusted_pvalues <- pvalues %>%
  arrange(pvalues) %>%
  mutate(p_bh = p.adjust(pvalues, method = "BH", n = length(pvalues))) %>%
  print(n = 30)
```

**Comment by zach-faunalytics** [comment]
Adding adjusted p-values.

I may be misunderstanding, but it works with the example you gave for glm as far as I can tell. Could you point me to the specific line numbers and file you tried it with in case that's why I'm getting a different result? Also the specific error it throws! It should be an easy fix with that. Just confirming you updated the p_name argument as needed? I had to do that when I ran it. Adding a warning to make that extra clear in case that's the issue.

**Comment by zach-faunalytics** [comment]
Also adding an option coef_vec argument. For the example you gave from Andrea's code, she doesn't use two of the (non-intercept) p-values in her adjustment, so I added an argument that lets you omit those (along the lines of the 2:11 part of her code, but hopefully more transparent).

**Comment by jo-faunalytics** [comment]
> Adding adjusted p-values.
> 
> I may be misunderstanding, but it works with the example you gave for glm as far as I can tell. Could you point me to the specific line numbers and file you tried it with in case that's why I'm getting a different result? Also the specific error it throws! It should be an easy fix with that. Just confirming you updated the p_name argument as needed? I had to do that when I ran it. Adding a warning to make that extra clear in case that's the issue.

Sorry about that! I pulled some setup and a model from file: "4.1 Inferentials_Effect Of Advocacy" , lines 42-43, and after loading the bh_adj function, ran it as:
`setwd("C:/Users/Jo/FaunaGitHub/relative-effectiveness-2")
#load libraries
library(tidyverse)
#load the data
load("RE Experiment_final.Rdata")
#reorder levels of advocacy type to set control as reference level
data$advocacytype <- relevel(data$advocacytype, ref = "control") 
#set contrasts for message
contrasts(data$message) = contr.sum(3)
logistic_model <- glm(dietpledge_bin ~ advocacytype + message, family = 'binomial', na.action = na.omit, data = data )
summary(logistic_model)
bh_adj(logistic_model)
`
The error I got was:

> Error in `rename()`:
> ! Can't rename columns that don't exist.
> ✖ Column `Pr(>|t|)` doesn't exist.

**Comment by zach-faunalytics** [comment]
I updated this in a a couple of ways:
- It now takes either an lm or glm model (e.g., m1 <- lm(mpg ~ cyl + hp + wt, data = mtcars);  bh_adj(m1)) instead of a summary object. If you give it a summary object, there's an error and a warning message.
- It looks for either "Pr(>|z|)" or "Pr(>|t|)" as the p-value name and works with either. If neither of those are present, you have to specify what p-value column name it should look for (using the p_name argument, which overrides the defaults). It throws a warning if this isn't done correctly.

To replicate Andrea's code, you'll need to do what she did with the [2:11] part. You can do that with the bh_adj function using the coef_vec (short for coefficient vector argument). You'd set that like this:
coef_vec = c("advocacytypenondisruptive", "advocacytypelabeled", "advocacytypebillboard", "advocacytypenewsarticle", "advocacytypedisruptive", "advocacytypenongraphic", "advocacytypeleaflet", "advocacytypegraphic", "advocacytypecelebrity", "advocacytypesocialmedia")

Hopefully that all makes sense and works, but let me know if there's any issues!

**Comment by zach-faunalytics** [comment]
Hi Jo! I just wanted to check if you think you'll have a chance to check these updates. I want to use this function for the Humanewashing code, but I can do it another way if not.

**Review by jo-faunalytics — APPROVED** [review]
Thanks for the nudge, this got lost in my inbox but it looks great. :)

**Comment by jo-faunalytics** [comment]
I don't have write access for the package so I can't merge and delete your branch, but you can go ahead.

**Pull request merged**
